language: rust

rust:
- 1.30.0
- stable
- beta
- nightly

os:
- linux
- osx
- windows

script:
- cargo build --verbose --all
- cargo test -- --nocapture --test-threads 1

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
